// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsyqkpktzqukomgzxlng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzeXFrcGt0enF1a29tZ3p4bG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTExNDMsImV4cCI6MjA3MDk4NzE0M30.iZs1O-UfNanRRvM0KOJAJ1Z_pAYwWaKA56Yuy0AkPPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});